import titanicS from "../images/titanicScene.png";
import tita from "../images/tit.png";
import tslookmom from "../images/tslookmom.jpg";
import spidey from "../images/spidey.png";
import jumanji from "../images/jumanji.png";
import wolf from "../images/wolf.png"
import mrs from "../images/mrs.png"
import hob from "../images/hob.png"
import spideyLogo from "../images/spideyLogo.png"
import spideyScene from "../images/spideyScene.png"
import moralis from "../images/moralis.png"
import moralisLogo from "../images/moralisLogo.png"
import moralisScene from "../images/moralisScene.png"
import jam from "../images/jam.png"
import jamLogo from "../images/jamLogo.png"
import jamScene from "../images/jamScene.png"
import bayw from "../images/bayw.png"
import shrek from "../images/shrek.png"
import lucy from "../images/lucy.png"
import topgu from "../images/topgu.png"
import imit from "../images/imit.png"
import reven from "../images/reven.png"
import tomb from "../images/tomb.png"
import amaz from "../images/amaz.png"
import bigs from "../images/bigs.png"
import secona from "../images/secona.png"
import ted from "../images/ted.png"
import amerp from "../images/amerp.png"


export const movies = [
    {
        Movie: "",
        Thumbnail: tita,
        Scene: titanicS,
        Logo: titanicS,
        Name: "Titanic",
        Description: "Staring Kate Winslet and Leonardo DiCaprio. The two play characters who are of different social classes. They fall in love after meeting aboard the ship, but it was not good for a rich girl to fall in love with a poor boy in 1912.",
        Genre: "Romance, Drama",
        Actors: "Kate Winslet, Leonardo DiCaprio",
        Year: "1998",
        Duration: "3h 14min",
    },
    {
        Movie: "",
        Thumbnail: spidey,
        Scene: spideyScene,
        Logo: spideyLogo,
        Name: "Spiderman Homecoming",
        Description: "Peter Parker tries to stop Vulture",
        Genre: "Action, Superhero, Comedy",
        Actors: "Tom Holland, Zendaya",
        Year: "2017",
        Duration: "2h 13min",
    },
    {
        Movie: "",
        Thumbnail: tslookmom,
        Scene: tslookmom,
        Logo: tslookmom,
        Name: "Titanic",
        Description: "Staring Kate Winslet and Leonardo DiCaprio. The two play characters who are of different social classes. They fall in love after meeting aboard the ship, but it was not good for a rich girl to fall in love with a poor boy in 1912.",
        Genre: "Romance, Drama",
        Actors: "Kate Winslet, Leonardo DiCaprio",
        Year: "1998",
        Duration: "3h 14min",
    },
    {
        Movie: "",
        Thumbnail: jumanji,
        Scene: "",
        Logo: "",
        Name: "Jumanji",
        Description: "",
        Genre: "",
        Actors: "",
        Year: "",
        Duration: "",
    },
    {
        Movie: "",
        Thumbnail: wolf,
        Scene: moralisScene,
        Logo: moralisLogo,
        Name: "",
        Description: "",
        Genre: "",
        Actors: "",
        Year: "",
        Duration: "1min 2sec",
    },
    {
        Movie: "",
        Thumbnail: jam,
        Scene: titanicS,
        Logo: "",
        Name: "",
        Description: "",
        Genre: "",
        Actors: "",
        Year: "",
        Duration: "",
    },
    {
        Movie: "",
        Thumbnail: mrs,
        Scene: "",
        Logo: "",
        Name: "Mr and Mrs Smith",
        Description: "",
        Genre: "",
        Actors: "",
        Year: "",
        Duration: "",
    },
    {
        Movie: "",
        Thumbnail: hob,     
        Scene: "",
        Logo: jamLogo,
        Name: "Jam Doughnut",
        Description: "",
        Genre: "Silent Mukbang",
        Actors: "Jay",
        Year: "2022",
        Duration: "1min 5sec",
    },
    {
        Movie: "",
        Thumbnail: spideyLogo,
        Scene: titanicS,
        Logo: titanicS,
        Name: "Titanic",
        Description: "Staring Kate Winslet and Leonardo DiCaprio. The two play characters who are of different social classes. They fall in love after meeting aboard the ship, but it was not good for a rich girl to fall in love with a poor boy in 1912.",
        Genre: "Romance, Drama",
        Actors: "Kate Winslet, Leonardo DiCaprio",
        Year: "1998",
        Duration: "3h 14min",
    },
    {
        Movie: "",
        Thumbnail: spideyScene,
        Scene: titanicS,
        Logo: titanicS,
        Name: "Titanic",
        Description: "Staring Kate Winslet and Leonardo DiCaprio. The two play characters who are of different social classes. They fall in love after meeting aboard the ship, but it was not good for a rich girl to fall in love with a poor boy in 1912.",
        Genre: "Romance, Drama",
        Actors: "Kate Winslet, Leonardo DiCaprio",
        Year: "1998",
        Duration: "3h 14min",
    },
    {
        Movie: "",
        Thumbnail: moralis,
        Scene: titanicS,
        Logo: titanicS,
        Name: "Titanic",
        Description: "Staring Kate Winslet and Leonardo DiCaprio. The two play characters who are of different social classes. They fall in love after meeting aboard the ship, but it was not good for a rich girl to fall in love with a poor boy in 1912.",
        Genre: "Romance, Drama",
        Actors: "Kate Winslet, Leonardo DiCaprio",
        Year: "1998",
        Duration: "3h 14min",
    },
    {
        Movie: "",
        Thumbnail: moralisLogo,
        Scene: titanicS,
        Logo: titanicS,
        Name: "Titanic",
        Description: "Staring Kate Winslet and Leonardo DiCaprio. The two play characters who are of different social classes. They fall in love after meeting aboard the ship, but it was not good for a rich girl to fall in love with a poor boy in 1912.",
        Genre: "Romance, Drama",
        Actors: "Kate Winslet, Leonardo DiCaprio",
        Year: "1998",
        Duration: "3h 14min",
    },
    {
        Movie: "",
        Thumbnail: moralisScene,
        Scene: titanicS,
        Logo: titanicS,
        Name: "Titanic",
        Description: "Staring Kate Winslet and Leonardo DiCaprio. The two play characters who are of different social classes. They fall in love after meeting aboard the ship, but it was not good for a rich girl to fall in love with a poor boy in 1912.",
        Genre: "Romance, Drama",
        Actors: "Kate Winslet, Leonardo DiCaprio",
        Year: "1998",
        Duration: "3h 14min",
    },
    {
        Movie: "",
        Thumbnail: jam,
        Scene: titanicS,
        Logo: titanicS,
        Name: "Titanic",
        Description: "Staring Kate Winslet and Leonardo DiCaprio. The two play characters who are of different social classes. They fall in love after meeting aboard the ship, but it was not good for a rich girl to fall in love with a poor boy in 1912.",
        Genre: "Romance, Drama",
        Actors: "Kate Winslet, Leonardo DiCaprio",
        Year: "1998",
        Duration: "3h 14min",
    },
    {
        Movie: "",
        Thumbnail: jamLogo,
        Scene: titanicS,
        Logo: titanicS,
        Name: "Titanic",
        Description: "Staring Kate Winslet and Leonardo DiCaprio. The two play characters who are of different social classes. They fall in love after meeting aboard the ship, but it was not good for a rich girl to fall in love with a poor boy in 1912.",
        Genre: "Romance, Drama",
        Actors: "Kate Winslet, Leonardo DiCaprio",
        Year: "1998",
        Duration: "3h 14min",
    },
    {
        Movie: "",
        Thumbnail: jamScene,
        Scene: titanicS,
        Logo: titanicS,
        Name: "Titanic",
        Description: "Staring Kate Winslet and Leonardo DiCaprio. The two play characters who are of different social classes. They fall in love after meeting aboard the ship, but it was not good for a rich girl to fall in love with a poor boy in 1912.",
        Genre: "Romance, Drama",
        Actors: "Kate Winslet, Leonardo DiCaprio",
        Year: "1998",
        Duration: "3h 14min",
    },
    {
        Movie: "",
        Thumbnail: bayw,
        Scene: titanicS,
        Logo: titanicS,
        Name: "Titanic",
        Description: "Staring Kate Winslet and Leonardo DiCaprio. The two play characters who are of different social classes. They fall in love after meeting aboard the ship, but it was not good for a rich girl to fall in love with a poor boy in 1912.",
        Genre: "Romance, Drama",
        Actors: "Kate Winslet, Leonardo DiCaprio",
        Year: "1998",
        Duration: "3h 14min",
    },
    {
        Movie: "",
        Thumbnail: shrek,
        Scene: titanicS,
        Logo: titanicS,
        Name: "Titanic",
        Description: "Staring Kate Winslet and Leonardo DiCaprio. The two play characters who are of different social classes. They fall in love after meeting aboard the ship, but it was not good for a rich girl to fall in love with a poor boy in 1912.",
        Genre: "Romance, Drama",
        Actors: "Kate Winslet, Leonardo DiCaprio",
        Year: "1998",
        Duration: "3h 14min",
    },
    {
        Movie: "",
        Thumbnail: lucy,
        Scene: titanicS,
        Logo: titanicS,
        Name: "Titanic",
        Description: "Staring Kate Winslet and Leonardo DiCaprio. The two play characters who are of different social classes. They fall in love after meeting aboard the ship, but it was not good for a rich girl to fall in love with a poor boy in 1912.",
        Genre: "Romance, Drama",
        Actors: "Kate Winslet, Leonardo DiCaprio",
        Year: "1998",
        Duration: "3h 14min",
    },
    {
        Movie: "",
        Thumbnail: topgu,
        Scene: titanicS,
        Logo: titanicS,
        Name: "Titanic",
        Description: "Staring Kate Winslet and Leonardo DiCaprio. The two play characters who are of different social classes. They fall in love after meeting aboard the ship, but it was not good for a rich girl to fall in love with a poor boy in 1912.",
        Genre: "Romance, Drama",
        Actors: "Kate Winslet, Leonardo DiCaprio",
        Year: "1998",
        Duration: "3h 14min",
    },
    {
        Movie: "",
        Thumbnail: imit,
        Scene: titanicS,
        Logo: titanicS,
        Name: "Titanic",
        Description: "Staring Kate Winslet and Leonardo DiCaprio. The two play characters who are of different social classes. They fall in love after meeting aboard the ship, but it was not good for a rich girl to fall in love with a poor boy in 1912.",
        Genre: "Romance, Drama",
        Actors: "Kate Winslet, Leonardo DiCaprio",
        Year: "1998",
        Duration: "3h 14min",
    },{
        Movie: "",
        Thumbnail: reven,
        Scene: titanicS,
        Logo: titanicS,
        Name: "Titanic",
        Description: "Staring Kate Winslet and Leonardo DiCaprio. The two play characters who are of different social classes. They fall in love after meeting aboard the ship, but it was not good for a rich girl to fall in love with a poor boy in 1912.",
        Genre: "Romance, Drama",
        Actors: "Kate Winslet, Leonardo DiCaprio",
        Year: "1998",
        Duration: "3h 14min",
    },{
        Movie: "",
        Thumbnail: tomb,
        Scene: titanicS,
        Logo: titanicS,
        Name: "Titanic",
        Description: "Staring Kate Winslet and Leonardo DiCaprio. The two play characters who are of different social classes. They fall in love after meeting aboard the ship, but it was not good for a rich girl to fall in love with a poor boy in 1912.",
        Genre: "Romance, Drama",
        Actors: "Kate Winslet, Leonardo DiCaprio",
        Year: "1998",
        Duration: "3h 14min",
    },{
        Movie: "",
        Thumbnail: amaz,
        Scene: titanicS,
        Logo: titanicS,
        Name: "Titanic",
        Description: "Staring Kate Winslet and Leonardo DiCaprio. The two play characters who are of different social classes. They fall in love after meeting aboard the ship, but it was not good for a rich girl to fall in love with a poor boy in 1912.",
        Genre: "Romance, Drama",
        Actors: "Kate Winslet, Leonardo DiCaprio",
        Year: "1998",
        Duration: "3h 14min",
    },{
        Movie: "",
        Thumbnail: bigs,
        Scene: titanicS,
        Logo: titanicS,
        Name: "Titanic",
        Description: "Staring Kate Winslet and Leonardo DiCaprio. The two play characters who are of different social classes. They fall in love after meeting aboard the ship, but it was not good for a rich girl to fall in love with a poor boy in 1912.",
        Genre: "Romance, Drama",
        Actors: "Kate Winslet, Leonardo DiCaprio",
        Year: "1998",
        Duration: "3h 14min",
    },{
        Movie: "",
        Thumbnail: secona,
        Scene: titanicS,
        Logo: titanicS,
        Name: "Titanic",
        Description: "Staring Kate Winslet and Leonardo DiCaprio. The two play characters who are of different social classes. They fall in love after meeting aboard the ship, but it was not good for a rich girl to fall in love with a poor boy in 1912.",
        Genre: "Romance, Drama",
        Actors: "Kate Winslet, Leonardo DiCaprio",
        Year: "1998",
        Duration: "3h 14min",
    },{
        Movie: "",
        Thumbnail: ted,
        Scene: titanicS,
        Logo: titanicS,
        Name: "Titanic",
        Description: "Staring Kate Winslet and Leonardo DiCaprio. The two play characters who are of different social classes. They fall in love after meeting aboard the ship, but it was not good for a rich girl to fall in love with a poor boy in 1912.",
        Genre: "Romance, Drama",
        Actors: "Kate Winslet, Leonardo DiCaprio",
        Year: "1998",
        Duration: "3h 14min",
    },
    {
        Movie: "",
        Thumbnail: amerp,
        Scene: titanicS,
        Logo: titanicS,
        Name: "Titanic",
        Description: "Staring Kate Winslet and Leonardo DiCaprio. The two play characters who are of different social classes. They fall in love after meeting aboard the ship, but it was not good for a rich girl to fall in love with a poor boy in 1912.",
        Genre: "Romance, Drama",
        Actors: "Kate Winslet, Leonardo DiCaprio",
        Year: "1998",
        Duration: "3h 14min",
    },
];